name: preparate_icfes_seminario
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^17.0.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
